# Generated by Django 3.1.5 on 2021-01-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210117_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.BooleanField(default=True),
        ),
    ]
