# Generated by Django 3.1.5 on 2021-01-22 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='followed_by',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='is_followed',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AddField(
            model_name='friend',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friend',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
